server:
  port: 8080

spring:
  application:
    name: sample

  config:
    import: optional:configserver:http://localhost:8888/

  cloud:
    config:
      uri: http://localhost:8888
      label: main
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          zkNodes: localhost:2181
          brokers: localhost:9092


management:
  endpoints:
    web:
      exposure:
        include: "*"
